export const two = 1 + 1

throw new Error('error')
